# Generated by Django 5.0.2 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imoveis_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Foto', models.ImageField(upload_to='imoveis_photos/')),
                ('Descrption', models.TextField()),
                ('Status', models.CharField(choices=[('Vendido', 'Vendido'), ('Disponível', 'Disponível')], max_length=12)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
