# Generated by Django 5.0.6 on 2024-05-29 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_admin', models.CharField(db_column='nome_admin', max_length=255)),
                ('foto_admin', models.ImageField(blank=True, db_column='foto_admin', null=True, upload_to='admins/')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corretor', models.CharField(db_column='nome_corretor', max_length=255)),
                ('foto_corretor', models.ImageField(blank=True, db_column='foto_corretor', null=True, upload_to='corretores/')),
                ('cpf_corretor', models.CharField(db_column='cpf_corretor', max_length=255)),
                ('rg_corretor', models.CharField(db_column='rg_corretor', max_length=255)),
                ('telefone_corretor', models.CharField(db_column='telefone_corretor', max_length=255)),
            ],
            options={
                'db_table': 'corretor',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro_endereco', models.CharField(db_column='logradouro_endereco', max_length=255)),
                ('numero_endereco', models.CharField(db_column='numero_endereco', max_length=255)),
                ('bairro_endereco', models.CharField(db_column='bairro_endereco', max_length=255)),
                ('cidade_endereco', models.CharField(db_column='cidade_endereco', max_length=255)),
                ('cep_endereco', models.CharField(db_column='cep_endereco', max_length=255)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='InfraestruturaEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_infraestrutura_emp', models.CharField(db_column='nome_infraestrutura_emp', max_length=255)),
            ],
            options={
                'db_table': 'infraestrutura_emp',
            },
        ),
        migrations.CreateModel(
            name='InfraestruturaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_infraestrutura_imovel', models.CharField(db_column='nome_infraestrutura_imovel', max_length=255)),
            ],
            options={
                'db_table': 'infraestrutura_imovel',
            },
        ),
        migrations.CreateModel(
            name='SubtipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subtipo_imovel', models.CharField(db_column='nome_subtipo_imovel', max_length=255)),
            ],
            options={
                'db_table': 'subtipo_imovel',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_cliente', models.CharField(db_column='nome_tipo_cliente', max_length=255)),
            ],
            options={
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_conta', models.CharField(db_column='nome_tipo_conta', max_length=255)),
            ],
            options={
                'db_table': 'tipo_conta',
            },
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_imovel', models.CharField(db_column='nome_tipo_imovel', max_length=255)),
            ],
            options={
                'db_table': 'tipo_imovel',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(db_column='nome_cliente', max_length=255)),
                ('foto_cliente', models.ImageField(blank=True, db_column='foto_cliente', null=True, upload_to='clientes/')),
                ('telefone_cliente', models.CharField(blank=True, db_column='telefone_cliente', max_length=255, null=True)),
                ('estagio_cliente', models.CharField(db_column='estagio_cliente', max_length=255)),
                ('fk_corretor', models.ForeignKey(blank=True, db_column='fk_corretor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.corretor')),
                ('tipo_cliente', models.ForeignKey(db_column='tipo_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.tipocliente')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.admin')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.cliente')),
                ('corretor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.corretor')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empreendimento', models.CharField(db_column='nome_empreendimento', max_length=255)),
                ('taxa_empreendimento', models.FloatField(blank=True, db_column='taxa_empreendimento', null=True)),
                ('fk_endereco', models.ForeignKey(db_column='fk_endereco', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.endereco')),
            ],
            options={
                'db_table': 'empreendimento',
            },
        ),
        migrations.CreateModel(
            name='FotoEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto_empreendimento', models.CharField(db_column='url_foto_empreendimento', max_length=255)),
                ('fk_empreendimento', models.ForeignKey(db_column='fk_empreendimento', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.empreendimento')),
            ],
            options={
                'db_table': 'foto_empreendimento',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao_imovel', models.DateTimeField(auto_now_add=True, db_column='data_criacao_imovel')),
                ('data_atualizacao_imovel', models.DateTimeField(auto_now=True, db_column='data_atualizacao_imovel', null=True)),
                ('complemento_endereco_imovel', models.CharField(blank=True, db_column='complemento_endereco_imovel', max_length=255, null=True)),
                ('area_total_imovel', models.FloatField(blank=True, db_column='area_total_imovel', null=True)),
                ('area_privativa_imovel', models.FloatField(blank=True, db_column='area_privativa_imovel', null=True)),
                ('preco_imovel', models.FloatField(db_column='preco_imovel')),
                ('num_quarto_imovel', models.IntegerField(db_column='num_quarto_imovel')),
                ('num_suite_imovel', models.IntegerField(db_column='num_suite_imovel')),
                ('num_banheiro_imovel', models.IntegerField(db_column='num_banheiro_imovel')),
                ('num_garagem_imovel', models.IntegerField(db_column='num_garagem_imovel')),
                ('fk_corretor', models.OneToOneField(db_column='fk_corretor', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.corretor')),
                ('fk_empreendimento', models.ForeignKey(blank=True, db_column='fk_empreendimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.empreendimento')),
                ('fk_endereco', models.ForeignKey(db_column='fk_endereco', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.endereco')),
                ('fk_proprietario', models.ForeignKey(db_column='fk_proprietario', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.cliente')),
                ('fk_tipo_imovel', models.ForeignKey(db_column='fk_tipo_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.tipoimovel')),
            ],
            options={
                'db_table': 'imovel',
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto_imovel', models.CharField(db_column='url_foto_imovel', max_length=255)),
                ('fk_imovel', models.ForeignKey(db_column='fk_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.imovel')),
            ],
            options={
                'db_table': 'foto_imovel',
            },
        ),
        migrations.CreateModel(
            name='AssocInfraEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_empreendimento', models.ForeignKey(db_column='fk_empreendimento', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.empreendimento')),
                ('fk_infraestrutura_emp', models.ForeignKey(db_column='fk_infraestrutura_emp', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.infraestruturaemp')),
            ],
            options={
                'db_table': 'assoc_infra_emp',
            },
        ),
        migrations.CreateModel(
            name='AssocInfraImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_imovel', models.ForeignKey(db_column='fk_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.imovel')),
                ('fk_infraestrutura_imovel', models.ForeignKey(db_column='fk_infraestrutura_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.infraestruturaimovel')),
            ],
            options={
                'db_table': 'assoc_infra_imovel',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro_perfil', models.CharField(blank=True, db_column='bairro_perfil', max_length=255, null=True)),
                ('area_total_perfil', models.FloatField(blank=True, db_column='area_total_perfil', null=True)),
                ('area_privativa_perfil', models.FloatField(blank=True, db_column='area_privativa_perfil', null=True)),
                ('preco_perfil', models.FloatField(blank=True, db_column='preco_perfil', null=True)),
                ('num_quarto_perfil', models.IntegerField(blank=True, db_column='num_quarto_perfil', null=True)),
                ('num_suite_perfil', models.IntegerField(blank=True, db_column='num_suite_perfil', null=True)),
                ('num_banheiro_perfil', models.IntegerField(blank=True, db_column='num_banheiro_perfil', null=True)),
                ('num_garagem_perfil', models.IntegerField(blank=True, db_column='num_garagem_perfil', null=True)),
                ('fk_cliente', models.ForeignKey(db_column='fk_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.cliente')),
                ('fk_subtipo_imovel', models.ForeignKey(blank=True, db_column='fk_subtipo_imovel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.subtipoimovel')),
                ('fk_tipo_imovel', models.ForeignKey(blank=True, db_column='fk_tipo_imovel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cad_users.tipoimovel')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='AssocInfraImPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_infraestrutura_imovel', models.ForeignKey(db_column='fk_infraestrutura_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.infraestruturaimovel')),
                ('fk_perfil', models.ForeignKey(db_column='fk_perfil', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.perfil')),
            ],
            options={
                'db_table': 'assoc_infra_im_perfil',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_origem', models.IntegerField(db_column='fk_origem')),
                ('email_conta', models.CharField(db_column='email_conta', max_length=255)),
                ('senha_conta', models.CharField(db_column='senha_conta', max_length=255)),
                ('fk_tipo_conta', models.ForeignKey(db_column='fk_tipo_conta', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.tipoconta')),
            ],
            options={
                'db_table': 'conta',
            },
        ),
        migrations.AddField(
            model_name='subtipoimovel',
            name='fk_tipo_imovel',
            field=models.ForeignKey(db_column='fk_tipo_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.tipoimovel'),
        ),
    ]
