# Generated by Django 5.0.6 on 2024-06-06 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0002_remove_imovel_fk_tipo_imovel_endereco_uf_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='fk_subtipo_imovel',
            field=models.ForeignKey(db_column='fk_subtipo_imovel', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.subtipoimovel'),
        ),
    ]
