# Generated by Django 5.0.4 on 2024-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0002_imoveis_s_criador_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='update_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='crated_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='Descrption',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='Foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='Name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='imoveis_s',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='area_privativa',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='area_total',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='banheiros',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='garagens',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='iptu',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='preco_condominio',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='preco_venda',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='quartos',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='rua',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='sacadas',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='salas',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imoveis_s',
            name='suites',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
