# Generated by Django 5.0.6 on 2024-06-10 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0004_alter_fotoempreendimento_url_foto_empreendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='fk_corretor',
            field=models.ForeignKey(db_column='fk_corretor', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.corretor'),
        ),
    ]
