# Generated by Django 5.0.6 on 2024-06-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_users', '0005_alter_imovel_fk_corretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.CreateModel(
            name='AssocClienteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cliente', models.ForeignKey(db_column='fk_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.cliente')),
                ('fk_tipo_cliente', models.ForeignKey(db_column='fk_tipo_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_cad_users.tipocliente')),
            ],
            options={
                'db_table': 'assoc_cliente_tipo',
            },
        ),
    ]
